# CP1521  Assignment 1

CC	= cc
CFLAGS	= -g -Wall -Werror -std=c99

.PHONY: all
all: scroll exe.s

scroll: scroll.o
scroll.o: scroll.c chars.h

exe.s: chars.s scroll.s
	@echo cat $+ \> $@
	@(echo "# THIS FILE IS AUTOGENERATED"; \
	 echo "# EDIT $+ INSTEAD"; echo; \
	 cat $+) > $@

.PHONY: clean
clean:
	rm -f scroll *.o exe.s core
